import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Header component
function Header() {
  return (
    <header className="bg-gray-100 dark:bg-gray-800 text-black dark:text-white p-4 z-50 shadow-md h-15">
      <div className="container mx-auto flex justify-center items-center">
        <h1 className="text-4xl font-bold">
          <Link href="/">Metaal</Link>
        </h1>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* Header is included here */}
        <main>{children}</main>
      </body>
    </html>
  );
}
